from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
TARGET = PROJECT_ROOT / "docs" / "00-project" / "PROJECT-MAP.md"

CONTENT = """# Project Map

**Status:** ACTIVE  
**Version:** 0.1  
**Document type:** Cumulative project map  
**Project:** Text Integrity Research

---

# 1. Purpose

This document is the top-level map of the project documentation.

It defines:

- the major project areas;
- the relationships between them;
- the purpose of each documentation layer;
- the authoritative location of project knowledge;
- the flow from scientific research to specification, implementation,
  validation and certification;
- the mechanism by which new knowledge is propagated through the project.

This document is intentionally architectural.

Detailed requirements, scientific findings, implementation specifications
and validation procedures belong in the documents referenced by this map.

---

# 2. Project Objective

The project investigates, scientifically and experimentally, textual
watermarking, watermark detection, AI-generated-text detection and textual
transformation.

The project must support:

- multilingual research;
- reproducible experimentation;
- preservation measurement;
- detector and watermark evolution;
- rigorous validation;
- continuous scientific updating;
- maintainable implementation architecture.

The project is designed so that research conclusions can evolve without
requiring the entire project documentation or software architecture to be
discarded and rebuilt.

---

# 3. Core Principle

The project is an evidence-driven system.

Scientific evidence must be traceable from:

```text
SOURCE
  ↓
RESEARCH
  ↓
EVIDENCE
  ↓
ANALYSIS
  ↓
REQUIREMENT
  ↓
ARCHITECTURE
  ↓
IMPLEMENTATION
  ↓
EXPERIMENT
  ↓
VALIDATION
  ↓
DECISION
```

No important project decision should depend solely on undocumented intuition.

---

# 4. Documentation Architecture

The project is divided into the following major areas:

```text
00-project
    ↓
01-governance
    ↓
02-research
    ↓
03-scientific-specification
    ↓
04-architecture
    ↓
05-validation
    ↓
06-security
    ↓
07-data
    ↓
08-development
    ↓
09-operations
    ↓
10-certification
```

These layers are logically connected but are not necessarily executed in a
strict linear order.

---

# 5. Area 00 — Project Control

Directory:

`docs/00-project/`

Purpose:

Provides the project's central control layer.

It contains the documents that maintain:

- assumptions;
- decisions;
- open questions;
- research sources;
- unresolved knowledge;
- documentation changes;
- global project structure.

## Authoritative files

### Project Map

`docs/00-project/PROJECT-MAP.md`

Top-level map of the entire project.

### Assumption Registry

`docs/00-project/ASSUMPTION-REGISTRY.md`

Records explicit assumptions and their status.

### Decision Log

`docs/00-project/DECISION-LOG.md`

Records project-level decisions and their rationale.

### Documentation Change Queue

`docs/00-project/DOCUMENTATION-CHANGE-QUEUE.md`

Records required updates generated by new knowledge.

### Knowledge Backlog

`docs/00-project/KNOWLEDGE-BACKLOG.md`

Records unresolved scientific or technical knowledge gaps.

### Open Questions

`docs/00-project/OPEN-QUESTIONS.md`

Records questions requiring explicit resolution.

### Research Registry

`docs/00-project/RESEARCH-REGISTRY.md`

Records scientific and technical sources used by the project.

---

# 6. Area 01 — Governance

Directory:

`docs/01-governance/`

Primary document:

`docs/01-governance/P00-project-governance.md`

Purpose:

Defines how the project itself is governed.

It establishes:

- roles;
- change control;
- documentation authority;
- review rules;
- decision rules;
- evidence requirements;
- autonomous development boundaries;
- quality gates.

---

# 7. Area 02 — Research

Directory:

`docs/02-research/`

Primary map:

`docs/02-research/RESEARCH-MAP.md`

Purpose:

Contains the scientific research system.

Research is divided into domains:

```text
R01 Literature Research Methodology
R02 Watermark Research
R03 Watermark Detection Research
R04 AI-Generated Text Detection Research
R05 Multilingual & Linguistic Research
R06 Transformation & Preservation Research
R07 Evaluation & Statistical Methodology
R08 Benchmark & Dataset Research
```

Research is continuously updated.

New evidence must be propagated to all materially affected project areas.

---

# 8. Area 03 — Scientific Specification

Directory:

`docs/03-scientific-specification/`

Primary map:

`docs/03-scientific-specification/SPECIFICATION-MAP.md`

Purpose:

Transforms validated research findings into explicit scientific and
functional requirements.

This layer defines what the system must achieve and how success is measured.

It must not silently introduce requirements unsupported by research,
project decisions or explicit assumptions.

---

# 9. Area 04 — Architecture

Directory:

`docs/04-architecture/`

Primary map:

`docs/04-architecture/ARCHITECTURE-MAP.md`

Purpose:

Defines the technical architecture required to satisfy the scientific
specification.

Architecture must prioritize:

- modularity;
- testability;
- replaceability;
- offline execution where required;
- deterministic local operation where required;
- controlled external integrations;
- future extensibility;
- component versioning;
- component deprecation.

---

# 10. Area 05 — Validation

Directory:

`docs/05-validation/`

Primary map:

`docs/05-validation/VALIDATION-MAP.md`

Purpose:

Defines how the system and its components are experimentally evaluated.

Validation must measure both:

- desired properties;
- unintended degradation.

Validation must be evidence-driven and reproducible.

---

# 11. Area 06 — Security

Directory:

`docs/06-security/`

Primary map:

`docs/06-security/SECURITY-MAP.md`

Purpose:

Defines the project's security model.

Security includes:

- supply-chain security;
- dependency integrity;
- dataset integrity;
- model/component integrity;
- external-service trust;
- update mechanisms;
- provenance;
- reproducibility;
- malicious or corrupted inputs;
- operational isolation.

---

# 12. Area 07 — Data

Directory:

`docs/07-data/`

Primary map:

`docs/07-data/DATA-MAP.md`

Purpose:

Defines datasets, data provenance, storage, versioning, licensing,
integrity and reproducibility.

The project must distinguish between:

- source data;
- generated experimental data;
- derived datasets;
- benchmark datasets;
- detector outputs;
- transformation outputs.

---

# 13. Area 08 — Development

Directory:

`docs/08-development/`

Primary map:

`docs/08-development/DEVELOPMENT-MAP.md`

Purpose:

Defines how the software is developed, tested, packaged and maintained.

Development must support autonomous implementation within an explicitly
defined safety and decision boundary.

---

# 14. Area 09 — Operations

Directory:

`docs/09-operations/`

Primary map:

`docs/09-operations/OPERATIONS-MAP.md`

Purpose:

Defines deployment, configuration, updates, monitoring, maintenance,
failure handling and lifecycle management.

Operational architecture must support component evolution without requiring
uncontrolled changes to the whole system.

---

# 15. Area 10 — Certification

Directory:

`docs/10-certification/`

Primary map:

`docs/10-certification/CERTIFICATION-MAP.md`

Purpose:

Defines the final evidence required before the software can be considered
scientifically and operationally acceptable.

Certification must be based on measurable criteria rather than subjective
inspection.

---

# 16. Global Dependency Graph

The major project relationship is:

```text
PROJECT CONTROL
      │
      ▼
GOVERNANCE
      │
      ▼
RESEARCH
      │
      ▼
SCIENTIFIC SPECIFICATION
      │
      ▼
ARCHITECTURE
      │
      ├───────────────┐
      ▼               ▼
DEVELOPMENT         DATA
      │               │
      └───────┬───────┘
              ▼
          VALIDATION
              │
              ▼
           SECURITY
              │
              ▼
          OPERATIONS
              │
              ▼
        CERTIFICATION
```

This is a conceptual dependency graph.

In practice, dependencies are bidirectional in several areas.

For example, validation results can force changes to the specification or
architecture.

---

# 17. Feedback Loops

The project must explicitly support feedback loops.

Important examples include:

```text
VALIDATION
    ↓
RESEARCH
```

```text
VALIDATION
    ↓
SPECIFICATION
```

```text
NEW SCIENTIFIC EVIDENCE
    ↓
DOCUMENTATION CHANGE QUEUE
    ↓
AFFECTED DOCUMENTS
```

```text
NEW WATERMARK / DETECTOR
    ↓
RESEARCH
    ↓
ARCHITECTURE
    ↓
IMPLEMENTATION
    ↓
VALIDATION
```

The project is therefore evolutionary rather than strictly linear.

---

# 18. Source-of-Truth Rules

Each category of information has a preferred authoritative location.

| Information | Authoritative location |
|---|---|
| Project structure | `PROJECT-MAP.md` |
| Assumptions | `ASSUMPTION-REGISTRY.md` |
| Decisions | `DECISION-LOG.md` |
| Research sources | `RESEARCH-REGISTRY.md` |
| Research structure | `RESEARCH-MAP.md` |
| Unresolved knowledge | `KNOWLEDGE-BACKLOG.md` |
| Open project questions | `OPEN-QUESTIONS.md` |
| Documentation changes | `DOCUMENTATION-CHANGE-QUEUE.md` |
| Governance | `P00-project-governance.md` |
| Scientific requirements | `03-scientific-specification/` |
| Architecture | `04-architecture/` |
| Validation | `05-validation/` |
| Security | `06-security/` |
| Data | `07-data/` |
| Development | `08-development/` |
| Operations | `09-operations/` |
| Certification | `10-certification/` |

---

# 19. Propagation Rule

When a new fact, discovery, experiment or decision materially affects the
project, it must be propagated.

The responsible process is:

```text
DISCOVERY
   ↓
REGISTER
   ↓
CLASSIFY
   ↓
IDENTIFY IMPACT
   ↓
QUEUE DOCUMENTATION CHANGES
   ↓
UPDATE AFFECTED DOCUMENTS
   ↓
VALIDATE CONSISTENCY
```

The existence of a new research document does not automatically mean the
project documentation is updated.

---

# 20. Documentation Consistency

The documentation system must maintain consistency between:

- maps;
- requirements;
- assumptions;
- decisions;
- research findings;
- architecture;
- validation;
- security;
- operations.

When inconsistency is discovered, it must be explicitly resolved.

---

# 21. Change Management

Changes may originate from:

- scientific literature;
- experimental results;
- new detectors;
- new watermark methodologies;
- new languages;
- security discoveries;
- implementation constraints;
- operational failures;
- dependency changes;
- newly identified risks.

Every material change must have traceability.

---

# 22. Future-Proofing

The project must be designed to accommodate:

- new watermark families;
- new watermark detectors;
- new AI detectors;
- new languages;
- new datasets;
- new evaluation methodologies;
- new scientific findings;
- new security requirements;
- retirement of obsolete components.

New functionality should be introduced as modular additions wherever
possible.

Obsolete functionality must be removable without destabilizing unrelated
components.

---

# 23. Component Lifecycle

Project components should support:

```text
PLANNED
   ↓
EXPERIMENTAL
   ↓
VALIDATED
   ↓
ACTIVE
   ↓
DEPRECATED
   ↓
RETIRED
```

A component may also become:

```text
SUPERSEDED
```

when replaced by a superior methodology.

---

# 24. Offline Execution Principle

The execution environment is conceptually separated from the research and
development environment.

Research and development may use external resources where permitted.

The operational software may be required to execute without AI services or
other cloud inference dependencies.

This distinction must remain explicit throughout the architecture and
validation documentation.

---

# 25. External Services

External services may be used where scientifically justified.

However, the project must explicitly record:

- what service is used;
- why it is used;
- what data leaves the local environment;
- how its result is incorporated;
- how its availability affects the system;
- whether an equivalent local fallback exists;
- whether its behavior can change independently of the project.

---

# 26. Autonomous Development

The software may be developed and maintained by AI-assisted development
systems.

This does not imply that the operational software itself uses AI.

The development process and execution architecture are separate concerns.

Autonomous development must operate inside the constraints established by:

- governance;
- scientific specification;
- architecture;
- security;
- validation;
- certification.

---

# 27. Development Safety Boundary

Autonomous development must not silently change:

- scientific acceptance criteria;
- security boundaries;
- data handling policy;
- privacy requirements;
- architectural invariants;
- certification criteria;
- project objectives.

Changes of this class require explicit project-level authorization.

Routine implementation, testing, refactoring and documentation maintenance
may be automated when they remain within approved boundaries.

---

# 28. Quality Gates

Major project transitions require evidence.

Examples:

```text
RESEARCH → SPECIFICATION
```

requires sufficient scientific evidence.

```text
SPECIFICATION → ARCHITECTURE
```

requires architectural consistency.

```text
ARCHITECTURE → DEVELOPMENT
```

requires implementability.

```text
DEVELOPMENT → VALIDATION
```

requires reproducible builds/tests.

```text
VALIDATION → CERTIFICATION
```

requires satisfaction of certification criteria.

---

# 29. No Premature Completion

The project must not be declared complete merely because:

- the software runs;
- tests pass;
- documentation exists;
- a detector produces a desired result.

Completion requires satisfaction of the scientifically defined acceptance
criteria.

---

# 30. Continuous Reassessment

The project must support periodic reassessment of:

- scientific evidence;
- detector landscape;
- watermark landscape;
- multilingual coverage;
- benchmarks;
- dependencies;
- security assumptions;
- operational requirements.

A previously valid conclusion may become obsolete.

---

# 31. Documentation Maintenance

Documentation is treated as part of the system.

It must therefore be:

- versioned;
- internally consistent;
- traceable;
- modular;
- maintainable;
- auditable.

New knowledge must not be allowed to accumulate only in chat history or
developer memory.

---

# 32. Autonomous Documentation Review

Before a major documentation tranche is considered complete, an automated
review should check:

- broken internal references;
- missing referenced files;
- contradictory statuses;
- orphaned requirements;
- unresolved placeholders;
- duplicate identifiers;
- inconsistent terminology;
- stale dependency references;
- missing change-queue entries;
- map/document inconsistencies.

The exact review mechanism is defined later in the development and governance
documentation.

---

# 33. Documentation Change Queue as Safety Net

When an idea emerges during research or implementation but cannot immediately
be integrated into the correct document, it must be placed in:

`docs/00-project/DOCUMENTATION-CHANGE-QUEUE.md`

This prevents useful ideas from being lost while avoiding uncontrolled edits
during active work.

---

# 34. Knowledge Backlog as Safety Net

When a question cannot yet be answered reliably, it belongs in:

`docs/00-project/KNOWLEDGE-BACKLOG.md`

It must not be converted into an unsupported requirement.

---

# 35. Decision Log as Safety Net

When a choice affects architecture, scientific methodology, validation or
project scope, it belongs in:

`docs/00-project/DECISION-LOG.md`

The decision should include rationale and consequences.

---

# 36. Assumption Registry as Safety Net

When the project must temporarily operate under an unverified premise, the
premise belongs in:

`docs/00-project/ASSUMPTION-REGISTRY.md`

Assumptions should have an owner, status and resolution path.

---

# 37. Project State Model

The project should conceptually progress through:

```text
RESEARCH
    ↓
SPECIFICATION
    ↓
ARCHITECTURE
    ↓
IMPLEMENTATION
    ↓
EXPERIMENTATION
    ↓
VALIDATION
    ↓
CERTIFICATION
    ↓
OPERATION
    ↓
CONTINUOUS RESEARCH
```

The final state is not static.

Operation feeds new observations back into research and validation.

---

# 38. Top-Level Completion Condition

The project is considered complete for a release only when:

- scientific requirements are defined;
- relevant evidence is documented;
- architecture satisfies requirements;
- implementation satisfies architecture;
- validation satisfies acceptance criteria;
- security requirements are satisfied;
- data provenance is documented;
- operational procedures exist;
- certification evidence exists;
- known limitations are explicitly recorded.

---

# 39. Final Principle

The project is not a one-time software build.

It is a maintainable scientific and engineering system whose knowledge,
requirements, architecture, implementation and validation must be able to
evolve together.

The documentation architecture exists to make that evolution controlled,
traceable and reviewable.
"""

def main():
    TARGET.parent.mkdir(parents=True, exist_ok=True)

    if TARGET.exists():
        backup = TARGET.with_name(TARGET.name + ".bak")
        backup.write_text(
            TARGET.read_text(encoding="utf-8"),
            encoding="utf-8"
        )
        print(f"Backup created: {backup}")

    TARGET.write_text(CONTENT, encoding="utf-8")

    print(f"Updated: {TARGET}")
    print(f"Lines: {len(CONTENT.splitlines())}")
    print("Project map written successfully.")

if __name__ == "__main__":
    main()
